name:                gg
version:             0.1.0.0
github:              "u-quark/gg"
license:             GPL-3.0-or-later
license-file:        LICENSE
author:              "Lefteris Kritikos"
maintainer:          "eleftherios.kritikos@gmail.com"
copyright:           "Lefteris Kritikos"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Git

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/u-quark/gg#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- time
- brick
- vty
- lens
- generic-lens
- vector
- process
- bytestring
- MissingH
- wreq
- directory
- http-client

library:
  source-dirs: src
  ghc-options:
  - -Wall
  extra-libraries:
  - git2
  exposed-modules:
    - Lib
    - GG.Actions.Common
    - GG.Actions.Rebase
    - GG.Actions.Undo
    - GG.Actions
    - GG.Main
    - GG.Repo
    - GG.Repo.Config
    - GG.State
    - GG.Timers
    - GG.UI
    - Libgit2.Types   # XXX order matters here: we need Libgit2/Types.chi to be produced first
    - Libgit2.OID
    - Libgit2
    - Libgit2.Utils
    - Libgit2.Errors
    - Libgit2.Global
    - Libgit2.Repository
    - Libgit2.Commit
    - Libgit2.Revwalk
    - Libgit2.Refs
    - Libgit2.Diff
    - Libgit2.StrArray
    - Libgit2.Config
    - Libgit2.Signature
    - Libgit2.Apply
    - Libgit2.Index
    - Libgit2.Tree
    - Libgit2.Merge
    - Libgit2.Reflog

executables:
  gg:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    extra-libraries:
    - git2
    dependencies:
    - gg

tests:
  gg-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    extra-libraries:
    - git2
    dependencies:
    - gg
