name:                gg
version:             0.1.0.0
github:              "u-quark/gg"
license:             BSD3
author:              "Lefteris Kritikos"
maintainer:          "eleftherios.kritikos@gmail.com"
copyright:           "Lefteris Kritikos"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Git

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/u-quark/gg#readme>

dependencies:
- base >= 4.7 && < 5
- time
- brick
- vty
- lens
- vector
- process
- bytestring

library:
  source-dirs: src
  ghc-options:
  - -Wall
  exposed-modules:
    - Lib
    - GG.State
    - GG.UI
    - GG.Repo
    - Libgit2.Types   # XXX order matters here: we need Libgit2/Types.chi to be produced first
    - Libgit2.OID
    - Libgit2
    - Libgit2.Utils
    - Libgit2.Errors
    - Libgit2.Global
    - Libgit2.Repository
    - Libgit2.Commit
    - Libgit2.Revwalk
    - Libgit2.Refs
    - Libgit2.Diff
    - Libgit2.StrArray

executables:
  gg:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gg

tests:
  gg-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gg
